services:
  - type: web
    name: timex
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn timex_project.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: timex_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: RENDER
        value: true
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false

databases:
  - name: timex_db
    plan: free
    databaseName: timex_db
    ipAllowList: []