services:
  - type: web
    name: timex
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn timex_project.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: timex_db
          property: connectionString
      - key: RENDER
        value: true
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_PASSWORD
        sync: false  # This means the value needs to be set manually in Render dashboard
    dependencies:
      - name: timex_db

databases:
  - name: timex_db
    plan: free
    databaseName: timex_production
    ipAllowList: []