# Generated by Django 5.1.7 on 2025-04-01 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracking', '0002_zeitarbeitsfirma_customuser_zeitarbeitsfirma'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Offen'), ('APPROVED', 'Bestätigt'), ('REJECTED', 'Abgelehnt')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='manager_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='entry_type',
            field=models.CharField(choices=[('KOMMEN', 'Kommen'), ('GEHEN', 'Gehen'), ('FEIERABEND', 'Feierabend')], max_length=10),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_tracking.timeentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
